config/routes.rb
TinyDribbble::Application.routes.draw do
  devise_for :users

  root to: 'site#home'
  match '/about',   to: 'site#about'
  match '/faq',    to: 'site#faq'
  match '/contact', to: 'site#contact'
  match '/shots/:id/like', to: 'shots#like', as: :like
  resources :shots, only: [:create, :destroy, :new, :index]

end

app/models/shot.rb
class Shot < ActiveRecord::Base
  attr_accessible :description, :image
  belongs_to :user
  has_attached_file :image, :styles => { :cropped => "400x300>" },
  :storage => :s3, :s3_credentials => S3_CREDENTIALS, url: ":s3_domain_url", path: "/:class/:attachment/:id_partition/:style/:filename'" #, :s3_credentials => "#{Rails.root}/config/s3.yml"
  has_and_belongs_to_many :fans, class_name: "User", join_table: "users_favorite_shots"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :recoverable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
          :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body
  has_many :shots
  has_and_belongs_to_many :favorite_shots, class_name: "Shot", join_table: "users_favorite_shots" 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/shots_controller.rb
class ShotsController < ApplicationController

  def index
    @shots = Shot.all
    if current_user.nil?
      @header_title = "All users shots"
    else
      @shots -= current_user.shots
      @header_title = "Other users shots"
    end
  end

  def create
    @shot = current_user.shots.build(params[:shot])
    begin
      if @shot.save
        flash[:notice] = "Shot created!"
        redirect_to root_url
      else
        render 'site/home'
      end
    rescue
      flash[:error] = "There has been an error uploading the image to AWS. Please try with a smaller file."
      redirect_to new_shot_path
    end
  end

  def destroy
  end

  def new
    @shot = current_user.shots.build
  end

  def like
    @id=params[:id]
    shot = Shot.find @id

    if !(shot.user.id == current_user.id || shot.fans.include?(current_user))
      shot.fans << current_user
      shot.save
    end

    @count = shot.fans.size
    respond_to do |format|
      format.html { redirect_to root_url }
      format.js
    end    
  end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def home
    if user_signed_in?
      @shots = current_user.shots
      @header_title = "My shots"
    else
      @shots = Shot.all
      @header_title = "All users shots"
    end

  end

  def about
  end

  def faq
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_messages
    return if flash.empty?
    alert_classes = { error: "error", notice: "success", alert: "error" }

    flash.collect do |name, msg|
      content_tag :div, { class: "alert alert-#{alert_classes[name]}"} do
        content_tag(:button, "\u00D7", type: "button", class: "close", "data-dismiss" => "alert") +
          msg
      end
    end.join("\n").html_safe
  end
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @title %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "tiny-dribbble", root_path, id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <% if user_signed_in? %>
                <li>
                  <%= link_to "Upload a job", {controller: "shots", action: "new"} %>
                </li>
                <li><%= link_to "My Shots", root_path %></li>
                <li><%= link_to "Other Users Shots", shots_path %></li>
              <% else %>
                <li><%= link_to "Users Shots", shots_path %></li>
               <% end %>
              <li><%= link_to "About", about_path %></li>
              <li>
                <% if user_signed_in? %>
                  <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
                <% else %>
                  <%= link_to "Sign in", new_user_session_path %>
                <% end %>
             </li>
            </ul>
          </nav>
        </div>
      </div>
    </header>
    <div class="container">
      <%= flash_messages %>
      <% if user_signed_in? %>
      <div class="row">
        <div class="span3 pull-right">
        Logged in as <strong><%= current_user.email %></strong>.
      </div>
      </div>
      <% end %>
      <%= yield %>
      <footer class="footer">
        <small>
          <a href="http://tinydribbble.herokuapp.com/">tiny-dribbble</a>
          by Juan Pieres
        </small>
        <nav>
          <ul>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "FAQ", faq_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
          </ul>
        </nav>
      </footer>      
    </div>
  </body>
</html>

app/views/shared/_thumbnails.html.erb
<div class="hero-unit">
  <h1>tiny-dribbble</h1>
  <h2>Home with fancy text.</h2>
    <% unless user_signed_in? %>
      <%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-small btn-primary" %>
    <% end %>
</div>
<div class="row-fluid">
  <h2><%= @header_title %></2>
</div>

<% unless @shots.empty? %>
  <% @shots.each_slice(4) do |ts|%>
    <div class="row-fluid">
      <ul class="thumbnails">
        <%= render ts %>
      </ul>
    </div>
  <% end  %>
<% end  %>

<% if user_signed_in? %>
  <%= link_to "Upload a job", {controller: "shots", action: "new"}, class: "btn btn-primary"%>
<% end %>
<script type="text/javascript">
  $(document).ready(function(){
    $("img").parent().hover(function() {
      $(this).stop().animate({opacity: "0.1"}, 'fast');
      $(this).parent().find(".shot-description").stop().animate({opacity: "1"}, 'fast');
      },
    function() {
      $(this).stop().animate({opacity: "1"}, 'fast');
      $(this).parent().find(".shot-description").stop().animate({opacity: "0"}, 'fast');
    });
    $('a').tooltip();
  });
</script>

app/views/shots/_form.html.erb
<h2>Upload a shot</h2>

<%= form_for @shot, :html => { :multipart => true } do |form| %>
      <div><%= form.label :description, "Description" %><br />
      <%= form.text_field :description %></div>
      <div><%= form.label :image, "Image" %><br />
      <%= form.file_field :image %></div>
      <div><%= form.submit "Submit" %></div>
<% end %>

app/views/shots/_shot.html.erb
<li class="span3">
  <div class="thumbnail" >
    <div class="shot-description">   
      <%= shot.description %>
    </div>
    <div class="shot-image" >
        <%= image_tag shot.image.url(:cropped) %>
    </div>
    <div class="caption">
      <h6>
        <%= shot.user.name %>
        <%= link_to like_path(:id => shot.id), { id: "shot_#{shot.id}", class: "pull-right", :"data-toggle" => "tooltip",  title: "I like this shot!", remote: true } do%>
          <%= content_tag(:i, '', class:"icon-heart" ) %>
          <%= shot.fans.size %>
        <% end %>
      </h6>
    </div>
  </div>
</li>

app/views/shots/index.html.erb
<%= render 'shared/thumbnails' %>

app/views/shots/like.html.erb
LIKE

app/views/shots/like.js.erb
var $contents = $("a#shot_<%= @id %>").contents();
$contents[$contents.length - 1].nodeValue = " <%= @count %>";

app/views/shots/new.html.erb
  <div class="row-fluid">
    <%= render 'shots/form' %>
 </div>

app/views/site/about.html.erb
<h1>Site#about</h1>
About
<p>Find me in app/views/site/about.html.erb</p>

app/views/site/contact.html.erb
<h1>Site#contact</h1>
Contact
<p>Find me in app/views/site/contact.html.erb</p>

app/views/site/faq.html.erb
<h1>Site#faq</h1>
FAQ
<p>Find me in app/views/site/faq.html.erb</p>

app/views/site/home.html.erb
<%= render 'shared/thumbnails' %>